import React, { useEffect, useRef, useState } from "react";
import { JobEditor, kindLabels, SchemaFields, schemaDefaults, useCatalogs } from "./ResearchForms";
import { JobDetail, JsonResult, ResearchJobs, ResearchTable, RunDetail } from "./ResearchJobs";
import { MarketKlineViewer, type KlineRange, type KlineMetric } from "./pages/market/kline";
import { ResearchCompare } from "./ResearchCompare";
import { SessionOverview } from "./pages/dailyTrade/SessionOverview";
import type { TradeSessionDetail, CashflowRow, SessionLogRow } from "./pages/dailyTrade/types";
import { research, type Catalogs } from "./researchClient";
import type { Artifact, Asset, Job, JobSpec, Page, Result, ReviewedFactor, Run, Schedule } from "./research.generated";

function Title({ children }: { children: React.ReactNode }) { return <div className="page-title"><h1>{children}</h1></div>; }
function Failure({ error }: { error: string }) { return error ? <p className="alert error" role="alert">{error}</p> : null; }
export function ResearchRuns({ mining = false }: { mining?: boolean }) {
  const [compared, setCompared] = useState<Run[]>([]);
  const [runs, setRuns] = useState<Run[]>([]); const [cursor, setCursor] = useState<string>(); const [next, setNext] = useState<string | null>(null); const [selected, setSelected] = useState(""); const [error, setError] = useState("");
  const refresh = async () => { try { const p = await research.get<Page<Run>>(`/runs?limit=50${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`); setRuns(p.items); setNext(p.next_cursor); setError(""); } catch (e) { setError(String(e)); } };
  useEffect(() => { void refresh(); }, [cursor]);
  return <section className="panel"><div className="panel-head"><h2>{mining ? "挖掘运行与产物" : "研究运行与回测结果"}</h2><button className="button small" onClick={refresh}>刷新</button></div><Failure error={error} />
    <div className="table-wrap"><table><thead><tr><th>比较</th><th>运行</th><th>任务</th><th>状态</th><th>产物</th><th>操作</th></tr></thead><tbody>{runs.filter(r => !mining || String(r.metadata.command).includes("mine")).map(r => <tr key={r.run_id}><td><input type="checkbox" aria-label={`比较 ${r.run_id}`} checked={compared.some(row => row.run_id === r.run_id)} disabled={!compared.some(row => row.run_id === r.run_id) && compared.length >= 8} onChange={e => setCompared(e.target.checked ? [...compared, r] : compared.filter(row => row.run_id !== r.run_id))} /></td><td><button className="button small" onClick={() => setSelected(r.run_id)}>{r.run_id}</button></td><td>{r.job_id || "历史关联未知 / CLI"}</td><td>{String(r.metadata.status || "")}</td><td>{r.artifacts.length}</td><td><button className="button small danger" onClick={async () => { if (!window.confirm("删除此运行记录及其产物访问入口？")) return; try { await research.delete(`/runs/${r.run_id}`); setSelected(""); await refresh(); } catch (e) { setError(String(e)); } }}>删除</button></td></tr>)}</tbody></table></div>
    <div className="action-row"><button className="button small" disabled={!cursor} onClick={() => setCursor(undefined)}>第一页</button><button className="button small" disabled={!next} onClick={() => setCursor(next || undefined)}>下一页</button></div>
    {!!compared.length && <><button className="button small" onClick={() => setCompared([])}>清除比较（最多 8 个运行）</button><ResearchCompare runs={compared} /></>}
    {selected && <RunDetail key={selected} runId={selected} />}
  </section>;
}
export function MiningPage() {
  const { catalogs, error } = useCatalogs();
  return <><Title>因子挖掘</Title><Failure error={error} /><div className="grid two"><section className="panel"><h2>自主因子挖掘</h2><JobEditor kinds={["mine"]} catalogs={catalogs} /></section><section className="panel"><h2>公式因子挖掘</h2><JobEditor kinds={["mine_aff", "mine_gp", "mine_rl"]} catalogs={catalogs} /></section></div><ResearchRuns mining /><ResearchJobs /></>;
}
export function BacktestPage() {
  const { catalogs, error } = useCatalogs();
  return <><Title>回测</Title><Failure error={error} /><div className="grid two"><section className="panel"><h2>因子回测</h2><p>可选择库内因子，或输入内联表达式数组，例如 <code>{'[{"name":"momentum","expression":"$close/(TS_MEAN($close,20)+1e-8)-1"}]'}</code>。</p><JobEditor kinds={["factor_backtest"]} catalogs={catalogs} /></section><section className="panel"><h2>策略复测</h2><JobEditor kinds={["strategy_backtest"]} catalogs={catalogs} /></section></div><ResearchRuns /><ResearchJobs /></>;
}
function AssetForm({ model, catalogs, initial, submit, title }: { model: string; catalogs?: Catalogs; initial?: Record<string, unknown>; submit: (value: Record<string, unknown>) => Promise<unknown>; title: string }) {
  const [value, setValue] = useState(initial || schemaDefaults(model)); const [error, setError] = useState(""); const [result, setResult] = useState<unknown>(); const [busy, setBusy] = useState(false);
  return <form onSubmit={async e => { e.preventDefault(); setError(""); setBusy(true); try { setResult(await submit(value)); } catch (e) { setError(String(e)); } finally { setBusy(false); } }}><h3>{title}</h3><SchemaFields name={model} value={value} onChange={setValue} catalogs={catalogs} /><Failure error={error} /><button className="button primary" disabled={busy}>保存</button>{result !== undefined && <JsonResult value={result} />}</form>;
}
function ReportExtractor({ refresh }: { refresh: () => Promise<void> }) {
  const [upload, setUpload] = useState(""); const [jobId, setJobId] = useState(""); const [drafts, setDrafts] = useState<ReviewedFactor[]>([]); const [selected, setSelected] = useState<string[]>([]); const [error, setError] = useState(""); const [result, setResult] = useState<unknown>();
  return <section className="panel"><h2>报告上传与因子审核</h2><input type="file" accept=".pdf" aria-label="上传研究报告" onChange={async e => { const file = e.target.files?.[0]; if (file) try { setUpload((await research.upload(file)).upload_id); } catch (e) { setError(String(e)); } }} />
    {upload && <><JobEditor key={upload} kinds={["report_factor_extract"]} initial={{ kind: "report_factor_extract", input: { upload_id: upload } } as JobSpec} onSubmit={async (spec, key) => { const job = await research.submit(spec, key); setJobId(job.job_id); return job; }} /><button className="button small" onClick={async () => { try { await research.delete(`/uploads/${upload}`); setUpload(""); } catch (e) { setError(String(e)); } }}>删除上传文件</button></>}
    <label>提取任务 ID<input value={jobId} onChange={e => setJobId(e.target.value)} /></label><button className="button" disabled={!jobId} onClick={async () => { try { const r = await research.get<Result>(`/jobs/${jobId}/result`); const factors = (r.summary as { factors?: ReviewedFactor[] } | null)?.factors; if (!factors) throw new Error(`提取结果尚不可用：${r.availability}`); setDrafts(factors); setSelected([]); } catch (e) { setError(String(e)); } }}>读取提取结果</button>
    {drafts.map((d, i) => <fieldset key={d.draft_id}><label className="inline-check"><input type="checkbox" checked={selected.includes(d.draft_id)} onChange={e => setSelected(e.target.checked ? [...selected, d.draft_id] : selected.filter(x => x !== d.draft_id))} />选择入库</label><input aria-label="因子名称" value={d.factor_name} onChange={e => setDrafts(drafts.map((r, n) => n === i ? { ...r, factor_name: e.target.value } : r))} /><textarea aria-label="因子表达式" value={d.factor_expression} onChange={e => setDrafts(drafts.map((r, n) => n === i ? { ...r, factor_expression: e.target.value } : r))} /><button className="button small" onClick={async () => { try { setResult(await research.post("/factors/validate", { expressions: [d.factor_expression] })); } catch (e) { setError(String(e)); } }}>验证表达式</button></fieldset>)}
    {!!selected.length && <button className="button primary" onClick={async () => { try { setResult(await research.post("/report-factors/commit", { job_id: jobId, factors: drafts.filter(d => selected.includes(d.draft_id)).map(d => ({ draft_id: d.draft_id, factor_name: d.factor_name, factor_expression: d.factor_expression, categories: d.categories || [] })) })); await refresh(); } catch (e) { setError(String(e)); } }}>保存选中因子</button>}
    <Failure error={error} />{result !== undefined && <JsonResult value={result} />}{jobId && <JobDetail key={jobId} jobId={jobId} />}
  </section>;
}
export function LibraryPage() {
  const { catalogs, error: catalogError, refresh } = useCatalogs(); const [tab, setTab] = useState("factors"); const [selected, setSelected] = useState<string[]>([]); const [editing, setEditing] = useState<Asset>(); const [error, setError] = useState(""); const [result, setResult] = useState<unknown>(); const [dataset, setDataset] = useState(""); const [expression, setExpression] = useState(""); const [category, setCategory] = useState(""); const [categoryFilter, setCategoryFilter] = useState(""); const [pageIndex, setPageIndex] = useState(0);
  const all = tab === "factors" ? catalogs?.factors : tab === "strategies" ? catalogs?.strategies : catalogs?.pools;
  const categories = catalogs?.categories?.map(c => c.name) || [...new Set((catalogs?.factors || []).flatMap(r => (r.metadata.categories || []) as string[]))];
  useEffect(() => setPageIndex(0), [tab, categoryFilter]);
  const rows = (all || []).filter(r => !categoryFilter || ((r.metadata.categories || []) as string[]).includes(categoryFilter));
  const action = async (fn: () => Promise<unknown>) => { setError(""); try { const value = await fn(); setResult(value); await refresh(); } catch (e) { setError(String(e)); } };
  const datasetPicker = <label>目标数据集<select value={dataset} onChange={e => setDataset(e.target.value)}><option value="">请选择</option>{catalogs?.datasets.map(d => <option key={d.dataset_id} value={d.dataset_id}>{d.label}</option>)}</select></label>;
  return <><Title>研究资产库</Title><Failure error={catalogError || error} /><div className="tabs">{[["factors", "因子库"], ["strategies", "策略库"], ["stock-pools", "股票池"]].map(([key, label]) => <button className={`button ${tab === key ? "primary" : ""}`} key={key} onClick={() => { setTab(key); setSelected([]); setEditing(undefined); setCategoryFilter(""); }}>{label}</button>)}</div>
    <div className="grid side"><section className="panel"><div className="panel-head"><h2>{tab}</h2><button className="button small" onClick={refresh}>刷新</button></div>
      {tab === "factors" && <label>按分类筛选<select value={categoryFilter} onChange={e => setCategoryFilter(e.target.value)}><option value="">全部</option>{categories.map(c => <option key={c}>{c}</option>)}</select></label>}
      <div className="table-wrap"><table><thead><tr><th>选择</th><th>名称</th><th>版本</th><th>内容</th><th>操作</th></tr></thead><tbody>{rows.slice(pageIndex * 50, (pageIndex + 1) * 50).map(r => <tr key={r.id}><td><input type="checkbox" aria-label={`选择 ${r.name}`} checked={selected.includes(r.id)} onChange={e => setSelected(e.target.checked ? [...selected, r.id] : selected.filter(id => id !== r.id))} /></td><td>{r.name}</td><td>{r.revision}</td><td><details><summary>{r.kind === "factor" ? String(r.metadata.expression) : "查看"}</summary><JsonResult value={r.metadata} /></details></td><td><div className="row-actions left"><button className="button small" onClick={() => setEditing(r)}>编辑</button><button className="button small danger" onClick={() => { if (window.confirm(`删除 ${r.name}？`)) void action(() => research.delete(`/${tab}/${r.id}${tab === "stock-pools" ? `?dataset_id=${encodeURIComponent(dataset)}` : ""}`, r.revision)); }}>删除</button></div></td></tr>)}</tbody></table></div>
      <p>共 {rows.length} 项 · 第 {pageIndex + 1} 页</p><div className="action-row"><button className="button small" disabled={pageIndex === 0} onClick={() => setPageIndex(p => p - 1)}>上一页资产</button><button className="button small" disabled={(pageIndex + 1) * 50 >= rows.length} onClick={() => setPageIndex(p => p + 1)}>下一页资产</button></div>
      {tab !== "factors" && datasetPicker}
      <div className="action-row"><button className="button" disabled={!selected.length} onClick={() => action(async () => { const artifact = await research.post<Artifact>(`/${tab}/export`, { ids: selected }); await research.download(artifact); return artifact; })}>导出选中资产</button></div>
      <label>导入 JSON / 因子 CSV<input type="file" accept={tab === "factors" ? ".csv,.json" : ".json"} onChange={e => { const file = e.target.files?.[0]; if (file) void action(async () => { const uploaded = await research.upload(file); return research.post(`/${tab}/import${tab !== "factors" && dataset ? `?dataset_id=${encodeURIComponent(dataset)}` : ""}`, uploaded); }); }} /></label>
      {editing && <AssetForm key={`${tab}:${editing.id}`} model={tab === "factors" ? "FactorUpdate" : tab === "strategies" ? "StrategyCreate" : "StockPoolUpdate"} title={`编辑 ${editing.name}（版本 ${editing.revision}）`} catalogs={catalogs} initial={tab === "strategies" ? ((editing.metadata.metadata as { research_recipe?: Record<string, unknown> })?.research_recipe || { name: editing.name }) : { name: editing.name, ...(tab === "factors" ? { categories: editing.metadata.categories } : { symbols: editing.metadata.symbols, description: editing.metadata.description, dataset_id: dataset }) }} submit={async value => { const r = await research.edit(`/${tab}/${editing.id}`, value, editing.revision, tab === "strategies" ? "PUT" : "PATCH"); await refresh(); return r; }} />}
      {result !== undefined && <JsonResult value={result} />}
    </section><aside className="panel"><AssetForm key={tab} model={tab === "factors" ? "FactorCreate" : tab === "strategies" ? "StrategyCreate" : "StockPoolCreate"} title="创建资产" catalogs={catalogs} submit={async value => { const r = await research.post(`/${tab}`, value); await refresh(); return r; }} />
      {tab === "factors" && <><h3>表达式验证</h3><textarea value={expression} aria-label="验证表达式" onChange={e => setExpression(e.target.value)} /><div className="action-row"><button className="button" onClick={() => action(() => research.post("/factors/validate", { expressions: [expression] }))}>验证</button><button className="button" onClick={() => action(() => research.get("/factor-dsl"))}>算子与时间语义</button><button className="button" onClick={() => action(() => research.get("/factors/duplicates"))}>检测重复因子</button></div>
        <h3>分类管理</h3><input value={category} onChange={e => setCategory(e.target.value)} placeholder="分类名称" /><button className="button" onClick={() => action(() => research.post("/factors/categories", { name: category }))}>创建分类</button>
        {catalogs?.categories?.map(c => <div className="action-row" key={c.id}><span>{c.name} · v{c.revision}</span><button className="button small" onClick={() => { const name = window.prompt("新的分类名称", c.name); if (name && name !== c.name) void action(() => research.edit(`/factors/categories/${c.id}`, { name }, c.revision)); }}>重命名分类</button><button className="button small danger" onClick={() => { if (window.confirm(`删除分类 ${c.name}？因子保留。`)) void action(() => research.delete(`/factors/categories/${c.id}`, c.revision)); }}>删除分类</button></div>)}
        <div className="action-row">{(["add", "remove", "set"] as const).map(op => <button className="button small" key={op} disabled={!selected.length || !category} onClick={() => action(() => research.post("/factors/categories/members", { op, category, factors: (catalogs?.factors || []).filter(r => selected.includes(r.id)).map(r => ({ id: r.id, revision: r.revision })) }))}>{op === "add" ? "添加分类" : op === "remove" ? "移除分类" : "设置分类"}</button>)}</div>
        {!!selected.length && <JobEditor key={selected.join(",")} kinds={["factor_backtest"]} catalogs={catalogs} initial={{ kind: "factor_backtest", input: { factor_source: { type: "library", factor_ids: selected } } } as JobSpec} />}
      </>}
    </aside></div>{tab === "factors" && <ReportExtractor refresh={refresh} />}<ResearchJobs />
  </>;
}
export function MarketPage() {
  const [range, setRange] = useState<KlineRange>("ALL"); const [metric, setMetric] = useState<KlineMetric>("volume");
  const { catalogs, error: catalogError } = useCatalogs(); const [dataset, setDataset] = useState(""); const [symbols, setSymbols] = useState<string[]>([]); const [symbol, setSymbol] = useState(""); const [rows, setRows] = useState<Record<string, unknown>[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [error, setError] = useState("");
  useEffect(() => { let active = true; setSymbol(""); setRows([]); if (dataset) void research.all<string>(`/datasets/${encodeURIComponent(dataset)}/symbols`).then(r => { if (active) setSymbols(r); }).catch(e => { if (active) setError(String(e)); }); return () => { active = false; }; }, [dataset]);
  const bars = async (next?: string) => { try { const r = await research.get<Page<Record<string, unknown>>>(`/datasets/${encodeURIComponent(dataset)}/bars?symbol=${encodeURIComponent(symbol)}${next ? `&cursor=${encodeURIComponent(next)}` : ""}`); setRows(r.items); setCursor(r.next_cursor); setError(""); } catch (e) { setError(String(e)); } };
  return <><Title>市场数据</Title><Failure error={catalogError || error} /><div className="grid two"><section className="panel"><h2>下载、更新与维护</h2><JobEditor kinds={["data"]} catalogs={catalogs} /></section><section className="panel"><h2>行情查询</h2><label>数据集<select value={dataset} onChange={e => setDataset(e.target.value)}><option value="">请选择</option>{catalogs?.datasets.map(d => <option key={d.dataset_id} value={d.dataset_id}>{d.label}</option>)}</select></label><label>股票<select value={symbol} onChange={e => setSymbol(e.target.value)}><option value="">请选择</option>{symbols.map(s => <option key={s}>{s}</option>)}</select></label><button className="button" disabled={!symbol} onClick={() => bars()}>查询</button><p>图表显示当前页行情（最多 200 条），可翻页查看其他日期。</p><MarketKlineViewer payload={{ symbol, rows }} symbol={symbol} range={range} onRangeChange={setRange} subMetric={metric} onSubMetricChange={setMetric} /><ResearchTable rows={rows} /><button className="button small" disabled={!cursor} onClick={() => cursor && bars(cursor)}>下一页行情</button></section></div><ResearchJobs /></>;
}
export function DailyTradePage() {
  const [overview, setOverview] = useState<TradeSessionDetail>();
  const selection = useRef(0);
  useEffect(() => () => { selection.current++; }, []);
  const { catalogs, error, refresh } = useCatalogs(); const [selected, setSelected] = useState<Asset>(); const [history, setHistory] = useState<Record<string, unknown>[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [failure, setFailure] = useState("");
  const readHistory = async (id: string, next?: string) => { const request = selection.current; try { const r = await research.get<Page<Record<string, unknown>>>(`/signal-sessions/${id}/history${next ? `?cursor=${encodeURIComponent(next)}` : ""}`); if (request === selection.current) { setHistory(r.items); setCursor(r.next_cursor); } } catch (e) { if (request === selection.current) setFailure(String(e)); } };
  const selectSession = async (asset: Asset) => {
    const request = ++selection.current;
    setSelected(asset); setOverview(undefined); setHistory([]); setCursor(null); setFailure(""); void readHistory(asset.id);
    try {
      const [detail, history, cashflows] = await Promise.all([
        research.get<Asset>(`/signal-sessions/${asset.id}`), research.all<SessionLogRow>(`/signal-sessions/${asset.id}/history`),
        research.all<CashflowRow>(`/signal-sessions/${asset.id}/cashflows`)]);
      if (request === selection.current) { setSelected(detail); setOverview({ ...(detail.metadata as unknown as TradeSessionDetail), history, cashflows }); }
    } catch (e) { if (request === selection.current) setFailure(String(e)); }
  };
  return <><Title>日频模拟</Title><Failure error={error || failure} /><div className="grid two"><section className="panel"><h2>日频信号</h2><p>preview 仅预览；advance 按会话和交易日推进状态。相同交易日的重复推进返回已提交结果。</p><JobEditor kinds={["daily_signals"]} catalogs={catalogs} /></section><section className="panel"><AssetForm model="SessionCreate" catalogs={catalogs} title="创建模拟会话" submit={async v => { const r = await research.post("/signal-sessions", v); await refresh(); return r; }} /></section></div>
    <section className="panel"><div className="panel-head"><h2>模拟会话</h2><button className="button small" onClick={refresh}>刷新</button></div><div className="action-row">{catalogs?.sessions.map(s => <button className="button" key={s.id} onClick={() => { void selectSession(s); }}>{s.name} · v{s.revision}</button>)}</div>
      {selected && <>{overview && <SessionOverview detail={overview} />}<JsonResult value={selected.metadata} /><AssetForm key={`${selected.id}:${selected.revision}`} model="CashChange" title="模拟资金调整" submit={async v => { const r = await research.edit(`/signal-sessions/${selected.id}/cash`, v, selected.revision, "POST"); await refresh(); selection.current++; setSelected(undefined); return r; }} /><button className="button danger" onClick={async () => { if (!window.confirm(`删除模拟会话 ${selected.name}？`)) return; try { await research.delete(`/signal-sessions/${selected.id}`, selected.revision); selection.current++; setSelected(undefined); await refresh(); } catch (e) { setFailure(String(e)); } }}>删除会话</button><ResearchTable rows={history} /><button className="button small" disabled={!cursor} onClick={() => cursor && readHistory(selected.id, cursor)}>下一页历史</button></>}
    </section><ResearchJobs /></>;
}
export function SchedulerPage() {
  const { catalogs, error: catalogError } = useCatalogs(); const [schedules, setSchedules] = useState<Schedule[]>([]); const [name, setName] = useState(""); const [time, setTime] = useState("16:30"); const [timezone, setTimezone] = useState("Asia/Shanghai"); const [editing, setEditing] = useState<Schedule>(); const [error, setError] = useState(""); const [runtime, setRuntime] = useState<unknown>();
  const refresh = async () => { try { setSchedules(await research.all<Schedule>("/schedules")); setRuntime(await research.get("/schedules/runtime/status")); setError(""); } catch (e) { setError(String(e)); } };
  useEffect(() => { void refresh(); }, []);
  return <><Title>研究调度</Title><Failure error={error || catalogError} /><div className="grid two"><section className="panel"><h2>{editing ? `编辑 ${editing.name} · v${editing.revision}` : "创建调度"}</h2><label>名称<input value={name} onChange={e => setName(e.target.value)} /></label><label>每日时间<input type="time" value={time} onChange={e => setTime(e.target.value)} /></label><label>时区<input value={timezone} onChange={e => setTimezone(e.target.value)} /></label>
    <JobEditor key={editing?.schedule_id || "new"} kinds={Object.keys(kindLabels) as JobSpec["kind"][]} catalogs={catalogs} initial={editing?.job || undefined} label="保存调度" onSubmit={async job => { if (!name.trim()) throw new Error("请填写调度名称"); const body = { name, time, timezone, job, enabled: editing?.enabled ?? true }; const r = editing ? await research.edit(`/schedules/${editing.schedule_id}`, body, editing.revision, "PUT") : await research.post("/schedules", body); setEditing(undefined); await refresh(); return r; }} />
    {editing && <button className="button" onClick={() => { setEditing(undefined); setName(""); }}>新建调度</button>}</section><section className="panel"><h2>运行状态</h2><JsonResult value={runtime} /><div className="action-row">{["start", "stop"].map(a => <button className="button" key={a} onClick={async () => { try { await research.post(`/schedules/runtime/${a}`); await refresh(); } catch (e) { setError(String(e)); } }}>{a === "start" ? "启用调度" : "暂停调度"}</button>)}</div>
    {schedules.map(s => <fieldset key={s.schedule_id}><legend>{s.name}</legend><p>{s.time} {s.timezone} · {s.enabled ? "启用" : "禁用"} · {s.last_error}</p><div className="action-row"><button className="button small" disabled={!s.job} onClick={() => { setEditing(s); setName(s.name); setTime(s.time); setTimezone(s.timezone); }}>编辑</button><button className="button small" disabled={!s.job} onClick={async () => { try { await research.edit(`/schedules/${s.schedule_id}`, { name: s.name, time: s.time, timezone: s.timezone, enabled: !s.enabled, job: s.job }, s.revision, "PUT"); await refresh(); } catch (e) { setError(String(e)); } }}>{s.enabled ? "禁用" : "启用"}</button><button className="button small" disabled={!s.job} onClick={async () => { try { await research.post(`/schedules/${s.schedule_id}/run`); await refresh(); window.dispatchEvent(new Event("research-jobs")); } catch (e) { setError(String(e)); } }}>立即运行</button><button className="button small danger" onClick={async () => { try { await research.delete(`/schedules/${s.schedule_id}`, s.revision); await refresh(); } catch (e) { setError(String(e)); } }}>删除</button></div></fieldset>)}
    </section></div><ResearchJobs /></>;
}
export function AdvancedResearch() {
  const { catalogs, error } = useCatalogs();
  return <section className="panel"><h2>研究操作</h2><Failure error={error} /><JobEditor kinds={Object.keys(kindLabels) as JobSpec["kind"][]} catalogs={catalogs} /></section>;
}
