"""Export standalone OpenAPI and deterministic TypeScript from the same schema.

Run with --check in CI. Requires only the Portal dependencies, no engine/data/LLM.
The small emitter handles the JSON Schema constructs emitted by Pydantic; unknown
constructs fail generation instead of silently weakening a client type.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


def ts(schema):
    if not schema:
        return "unknown"
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(v, ensure_ascii=False) for v in schema["enum"])
    for key in ("anyOf", "oneOf", "allOf"):
        if key in schema:
            return "(" + (" & " if key == "allOf" else " | ").join(ts(v) for v in schema[key]) + ")"
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(ts({**schema, "type": k}) for k in kind)
    if kind in {"string", "boolean", "null"}:
        return kind
    if kind in {"number", "integer"}:
        return "number"
    if kind == "array":
        return f"Array<{ts(schema.get('items', {}))}>"
    if kind == "object":
        fields = [f'{json.dumps(k)}{"" if k in schema.get("required", []) else "?"}: {ts(v)};'
                  for k, v in schema.get("properties", {}).items()]
        additional = schema.get("additionalProperties")
        if additional:
            fields.append(f"[key: string]: {ts(additional) if isinstance(additional, dict) else 'unknown'};")
        return "{ " + " ".join(fields) + " }"
    raise ValueError(f"Unsupported schema: {schema}")


def build():
    from fastapi import FastAPI
    from fastapi.openapi.utils import get_openapi
    from alphapilot.research.api import install
    from alphapilot.research.models import ASSET_BUNDLE_ADAPTER
    app = FastAPI()
    install(app, lambda: None)
    schema = get_openapi(title="AlphaPilot Research API", version="1.0.0", routes=app.state.research_router.routes)
    schemas = schema["components"]["schemas"]
    source = "// Generated by scripts/export_research_contract.py. Do not edit.\n"
    source += "\n".join(f"export type {name} = {ts(body)};" for name, body in sorted(schemas.items()))
    job = schema["paths"]["/api/v1/jobs"]["post"]["requestBody"]["content"]["application/json"]["schema"]
    source += f"\nexport type JobSpec = {ts(job)};\n"
    source += "export type Page<T> = { items: T[]; next_cursor: string | null; total?: number | null };\n"
    return {ROOT / "docs/research/openapi-v1.json": json.dumps(schema, ensure_ascii=False, indent=2) + "\n",
            ROOT / "docs/research/asset-bundles-v1.schema.json": json.dumps({"$schema": "https://json-schema.org/draft/2020-12/schema", **ASSET_BUNDLE_ADAPTER.json_schema()}, ensure_ascii=False, indent=2) + "\n",
            ROOT / "alphapilot/modules/portal/web/src/research.generated.ts": source,
            ROOT / "alphapilot/modules/portal/web/src/research.schema.json": json.dumps(schemas, ensure_ascii=False, indent=2) + "\n"}


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in build().items():
        if args.check:
            if not path.is_file() or path.read_text() != content:
                raise SystemExit(f"Stale generated contract: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
